# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
# google-ID: ''

menu:
- {name: 'About me', folder: 'pages', file: 'about-me.html'}
- {name: 'Publications', folder: 'pages', file: 'publications.html'}
- {name: 'Posts', folder: 'pages', file: 'posts.html'}
- {name: 'Projects', folder: 'pages', file: 'documentation.html'}
- {name: 'CV', folder: 'cv-folder', file: 'CV_HSpark.pdf'}
- {name: 'Contact', folder: 'pages', file: 'contact.md'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/HeesunPark4'}
#- {icon: 'facebook', link: 'https://www.facebook.com/Le.Paul.94'}
#- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'envelope', link: 'mailto:heesunpark26@gmail.com'}
# - {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
